export type Offres_apprentissages = {
  "UAI formation": string;
  "UAI Responsable": string;
  "UAI formateur": string;
  "Code du diplome ou du titre suivant la nomenclature de l'Education nationale (CodeEN)": string;
  "Niveau de la formation": string;
  Tags: string;

  // "Fiche catalogue": string;
  // "Numero academie": string;
  // "Nom academie": string;
  // "Numero departement": string;
  // "Siret Responsable": string;
  // "UAI Responsable": string;
  // "Raison sociale de l'organisme responsable": string;
  // "Enseigne Responsable": string;
  // "Siret Formateur": string;
  // "UAI formateur": string;
  // "Enseigne Formateur": string;
  // "Raison sociale du siret formateur": string;
  // "Gestionnaire certifié qualité ? ": string;
  // "Formateur certifié qualité ? ": string;
  // Diplome: string;
  // "Intitule long de la formation": string;
  // "Intitule court de la formation": string;
  // "Intitule Carif-Oref": string;
  // "Organisme Habilite (RNCP)": string;
  // "Eligible apprentissage (RNCP)": string;
  // "Codes RNCP": string;
  // "Etat fiche RNCP": string;
  // code_type_certif: string;
  // type_certif: string;
  // "Intitule du code RNCP": string;
  // Certificateurs: string;
  // "Codes ROME": string;
  // "Code du diplome ou du titre suivant la nomenclature de l'Education nationale (CodeEN)": string;
  // "Code du diplome de l'année d'entrée": string;
  // "Liste MEF rattaches": string;
  // "Dates d'expiration MEF rattaches": string;
  // "Liste MEF Affelnet": string;
  // "Dates d'expiration MEF Affelnet": string;
  // "Liste MEF Parcoursup": string;
  // "Dates d'expiration MEF Parcoursup": string;
  // "Périmètre Affelnet": string;
  // "Statut Affelnet": string;
  // "Statut sur la précédente campagne Affelnet": string;
  // "Session sur la campagne Affelnet": string;
  // "Session sur la précédente campagne Affelnet": string;
  // "Information Affelnet": string;
  // "Information Affelnet (url)": string;
  // "Modalités particulières": string;
  // "Modalités particulières (url)": string;
  // "Motif de non publication Affelnet": string;
  // "Périmètre Parcoursup": string;
  // "Statut Parcoursup": string;
  // "Statut sur la précédente campagne Parcoursup": string;
  // "Session sur la campagne Parcoursup": string;
  // "Session sur la précédente campagne Parcoursup": string;
  // "Date du dernier envoi vers Parcoursup": string;
  // "Motif de non publication Parcoursup": string;
  // "Motif de rejet Parcoursup": string;
  // "Motif de la réinitialisation de statut Parcoursup": string;
  // "Date de la réinitialisation de statut Parcoursup": string;
  // "Niveau de la formation": string;
  // "Dates de formation": string;
  // Capacite: string;
  // Duree: string;
  // Annee: string;
  // "UAI formation": string;
  // "Edition de l'UAI formation": string;
  // "Date d’édition de l’UAI lieu": string;
  // "Modification de l’UAI lieu par": string;
  // "Adresse formation": string;
  // "Code Postal": string;
  // Ville: string;
  // "Code Commune Insee": string;
  // Geolocalisation: string;
  // "Distance entre le lieu de formation et l'établissement formateur": string;
  // "Numero Academie Siege": string;
  // "Nom Academie Siege": string;
  // "Url ONISEP": string;
  // "Eligible au catalogue général ?": string;
  // "Clé ministere educatif": string;
  // "parcoursup_id (g_ta_cod)": string;
  // "affelnet_id (code vœu)": string;
  // Partenaires: string;
  // "Adresse OFA formateur": string;
  // "Code Postal OFA formateur": string;
  // "Ville OFA formateur": string;
  // "Code Commune Insee OFA formateur": string;
  // "Nda gestionnaire": string;
  // "Nda formateur": string;
  // "Id RCO Info": string;
  // "id RCO formation": string;
  // "id RCO action": string;
  // "id RCO certifinfo": string;
  // "Date de fermeture du CFD": string;
  // "Date de fermeture du CFD de l'année d'entrée": string;
  // "Date de fin de validite au RNCP": string;
  // Tags: string;
  // "Etablissement gestionnaire actif": string;
  // "Etablissement formateur_actif": string;
  // Region: string;
  // "Siret Actif": string;
};
