stages:
  - sonarqube
  - ci
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

workflow:
  rules:
    # Pipeline automatique sur merge request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Pipeline automatique sur develop et main
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"
    # Pipeline manuel avec inputs
    - if: $CI_PIPELINE_SOURCE == "web"

include:
  - local: '.gitlab/ci/sonarqube.yml'
  - local: '.gitlab/ci/ci.yml'
  - local: '.gitlab/ci/release.yml'
  - local: '.gitlab/ci/deploy.yml'
