# Override containers for local / dev environnement
services:
  reverse_proxy:
    build:
      args:
        - DIR=dev
    volumes:
      - pilotage_nginx_data:/data:z
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - smtp

  postgres:
    image: postgres:15.5
    container_name: pilotage_postgres
    restart: unless-stopped
    networks:
      - pilotage_network
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pilotage_postgres_data:/var/lib/postgresql/data:z

  smtp:
    image: axllent/mailpit:v1.5.5
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
      rollback_config:
        parallelism: 0
    networks:
      - pilotage_network
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - pilotage_mailpit_data:/data
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_WEBROOT=smtp

volumes:
  pilotage_postgres_data:
    driver: local
    name: pilotage_postgres_data
  pilotage_mailpit_data:
    driver: local
    name: pilotage_mailpit_data
  pilotage_mailpit_auth:
    driver: local
    name: pilotage_mailpit_auth
  pilotage_nginx_data:
    driver: local
    name: pilotage_nginx_data
