services:
  postgres:
    image: postgres:15.5
    container_name: pilotage_postgres_db_test
    restart: unless-stopped
    networks:
      - pilotage_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pilotage_postgres_test_data:/var/lib/postgresql/data:z

networks:
  pilotage_network:
    external: true

volumes:
  pilotage_postgres_test_data:
