# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    build:
      args:
        - DIR=dev
    volumes:
      - pilotage_nginx_data:/data:z
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pilotage_postgres_data:/var/lib/postgresql/data:z

volumes:
  pilotage_postgres_data:
    driver: local
    name: pilotage_postgres_data
  pilotage_nginx_data:
    driver: local
    name: pilotage_nginx_data
  pilotage_server_data:
    driver: local
    name: pilotage_server_data
