- name: Assurer que ufw est installé
  package:
    name: ufw
    state: present
  when: ansible_os_family == "Debian" or ansible_distribution == "Ubuntu"

- name: Assurer que ufw est activé
  ufw:
    state: enabled

- name: Bloquer le port 5432 en entrée (TCP)
  ufw:
    rule: deny
    port: 5432
    proto: tcp

- name: Bloquer le port 5432 en entrée (UDP)
  ufw:
    rule: deny
    port: 5432
    proto: udp

- name: Vérifier le statut d'ufw
  command: ufw status
  register: ufw_status

- debug:
    msg: "{{ ufw_status.stdout }}"
