import type { ExportColumns } from "@/utils/downloadExport";

import type { Demandes } from "./types";

export const DEMANDES_COLUMNS = {
  rapprochement: "Rapprochement",
  motifRapprochement: "Motif rapprochement",
  numero: "N°Demande",
  cfd: "CFD",
  libelleFormation: "Diplôme",
  codeDispositif: "Code dispositif",
  libelleDispositif: "Dispositif",
  libelleFCIL: "Libellé de la FCIL",
  uai: "UAI",
  libelleEtablissement: "Établissement",
  codeRegion: "Code Region",
  libelleRegion: "Région",
  codeAcademie: "Code Académie",
  libelleAcademie: "Académie",
  codeDepartement: "Code Département",
  libelleDepartement: "Dpt.",
  rentreeScolaire: "RS",
  typeDemande: "Type",
  motif: "Motif",
  autreMotif: "Autre motif",
  coloration: "Coloration",
  libelleColoration: "Libellé(s) coloration(s)",
  amiCma: "AMI/CMA ?",
  commentaire: "Commentaire",
  statut: "Statut",
  createdAt: "Créé le",
  updatedAt: "Der. modif.",
  capaciteScolaireActuelle: "Capacité actuelle en voie scolaire",
  capaciteScolaire: "Future capacité en voie scolaire",
  capaciteScolaireColoreeActuelle: "Capacité colorée actuelle en voie scolaire",
  capaciteScolaireColoree: "Future capacité colorée en voie scolaire",
  capaciteApprentissageActuelle: "Capacité actuelle en apprentissage",
  capaciteApprentissage: "Future capacité en apprentissage",
  capaciteApprentissageColoreeActuelle: "Capacité colorée actuelle en apprentissage",
  capaciteApprentissageColoree: "Future capacité colorée en apprentissage",
  formationRH: "Formation(s) ?",
  nbFormationRH: "Nombre de formations",
  discipline1FormationRH: "Discipline 1 formation",
  discipline2FormationRH: "Discipline 2 formation",
  professeurAssocieRH: "Professeur(s) associé(s) ?",
  nbProfesseurAssocieRH: "Nombre de professeurs associés",
  discipline1ProfesseurAssocieRH: "Discipline 1 professeur associé",
  discipline2ProfesseurAssocieRH: "Discipline 2 professeur associé",
  reconversionRH: "Reconversion(s) ?",
  nbReconversionRH: "Nombre de reconversions",
  discipline1ReconversionRH: "Discipline 1 reconversion",
  discipline2ReconversionRH: "Discipline 2 reconversion",
  recrutementRH: "Recrutement(s) ?",
  nbRecrutementRH: "Nombre de recrutements",
  discipline1RecrutementRH: "Discipline 1 recrutement",
  discipline2RecrutementRH: "Discipline 2 recrutement",
  userName: "Auteur",
  inspecteurReferent: "Inspecteur",
  avis0: "Avis 1",
  avis1: "Avis 2",
  avis2: "Avis 3",
  avis3: "Avis 4",
  avis4: "Avis 5",
  avis5: "Avis 6",
  avis6: "Avis 7",
  avis7: "Avis 8",
  avis8: "Avis 9",
  avis9: "Avis 10",
  lastChangementStatutCommentaire: "Commentaire du dernier changement de statut",
} satisfies ExportColumns<
  Demandes[number] & {
    [key: `avis${number}`]: string;
  } & {
    libelleColoration?: string;
  }
>;

export const DEMANDES_COLUMNS_OPTIONAL = {
  rapprochement: "Rapprochement",
  updatedAt: "Der. modif.",
  cfd: "CFD",
  libelleFormation: "Diplôme",
  codeDispositif: "Code dispositif",
  libelleDispositif: "Dispositif",
  libelleFCIL: "Libellé de la FCIL",
  uai: "UAI",
  libelleEtablissement: "Établissement",
  codeRegion: "Code Region",
  libelleRegion: "Région",
  codeAcademie: "Code Académie",
  libelleAcademie: "Académie",
  codeDepartement: "Code Département",
  libelleDepartement: "Dpt.",
  rentreeScolaire: "RS",
  statut: "Statut",
  actions: "Actions",
  typeDemande: "Type",
  createdAt: "Créé le",
  numero: "N°Demande",
  userName: "Auteur",
  inspecteurReferent: "Inspecteur",
  motif: "Motif",
  autreMotif: "Autre motif",
  coloration: "Coloration",
  libelleColoration: "Libellé(s) coloration(s)",
  amiCma: "AMI/CMA ?",
  commentaire: "Commentaire",
  capaciteScolaireActuelle: "Capacité actuelle en voie scolaire",
  capaciteScolaire: "Future capacité en voie scolaire",
  capaciteScolaireColoreeActuelle: "Capacité colorée actuelle en voie scolaire",
  capaciteScolaireColoree: "Future capacité colorée en voie scolaire",
  capaciteApprentissageActuelle: "Capacité actuelle en apprentissage",
  capaciteApprentissage: "Future capacité en apprentissage",
  capaciteApprentissageColoreeActuelle: "Capacité colorée actuelle en apprentissage",
  capaciteApprentissageColoree: "Future capacité colorée en apprentissage",
  progression: "Progression",
  avisPhaseEnCours: "Avis - phase en cours",
  derniersAvisPhaseEnCours: "Derniers avis - phase en cours",
} satisfies Partial<typeof DEMANDES_COLUMNS> & {
  actions: string;
  progression: string;
  avisPhaseEnCours: string;
  derniersAvisPhaseEnCours: string;
};

export const DEMANDES_COLUMNS_DEFAULT = {
  rapprochement: "Rapprochement",
  updatedAt: "Der. modif.",
  libelleFormation: "Diplôme",
  libelleEtablissement: "Établissement",
  libelleDepartement: "Dpt.",
  statut: "Statut",
  actions: "Actions",
  typeDemande: "Type",
  createdAt: "Créé le",
  numero: "N°Demande",
  userName: "Auteur",
  inspecteurReferent: "Inspecteur",
  progression: "Progression",
  avisPhaseEnCours: "Avis - phase en cours",
  derniersAvisPhaseEnCours: "Derniers avis - phase en cours",
} satisfies Partial<typeof DEMANDES_COLUMNS_OPTIONAL>;
