version: "3.8"

# The following variables define reusable configurations for deployment, providing consistent and predefined
# behaviors for updating, rolling back, and restarting services.

x-deploy-default: &deploy-default
  update_config:
    failure_action: rollback
    parallelism: 1
    delay: 10s
  rollback_config:
    parallelism: 1
    delay: 10s
  restart_policy:
    condition: on-failure
    window: 360s
    delay: 30s
    # Max 24hours
    max_attempts: 240

x-default: &default
  networks:
    - ij_network

services:
  metabase:
    <<: *default
    image: metabase/metabase:v0.49.11
    deploy:
      <<: *deploy-default
      resources:
        limits:
          memory: 2g
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_SITE_LOCALE: fr
      MB_SITE_URL: "{{dns_name}}/metabase"
      MB_DB_TYPE: postgres
      MB_DB_CONNECTION_URI: "{{vault[env_name].METABASE_DB_URI}}"
      MB_EMAIL_FROM_ADDRESS: "{{vault.METABASE_EMAIL_FROM_ADDRESS}}"
      MB_EMAIL_FROM_NAME: "{{vault.METABASE_EMAIL_FROM_NAME}}"
      MB_PASSWORD_COMPLEXITY: strong
      MB_START_OF_WEEK: monday
      MB_EMAIL_SMTP_HOST: "{{vault[env_name].SMTP_HOST}}"
      MB_EMAIL_SMTP_PORT: "{{vault[env_name].SMTP_PORT}}"
      MB_EMAIL_SMTP_USERNAME: "{{vault[env_name].SMTP_AUTH_USER}}"
      MB_EMAIL_SMTP_PASSWORD: "{{vault[env_name].SMTP_AUTH_PASS}}"
      MB_EMAIL_SMTP_SECURITY: tls
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 6m
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.json.{{product_name}}.{{env_name}}.metabase
        fluentd-async: "true"
