version: "3.8"

# The following variables define reusable configurations for deployment, providing consistent and predefined
# behaviors for updating, rolling back, and restarting services.

x-deploy-default: &deploy-default
  update_config:
    failure_action: rollback
    parallelism: 1
    delay: 10s
  rollback_config:
    parallelism: 1
    delay: 10s
  restart_policy:
    condition: on-failure
    window: 360s
    delay: 30s
    # Max 24hours
    max_attempts: 240

x-default: &default
  networks:
    - ij_network

services:
  server:
    <<: *default
    image: ghcr.io/mission-apprentissage/ij_{{product_name}}_server:{{app_version}}
    deploy:
      <<: *deploy-default
      resources:
        limits:
          memory: 2g
      replicas: 2
    stop_grace_period: 60s
    volumes:
      - /opt/app/data/server:/data
      - /opt/app/.env_server:/app/server/.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.json.{{product_name}}.{{env_name}}.server
        fluentd-async: "true"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 11
      start_period: 10s

  ui:
    <<: *default
    image: ghcr.io/mission-apprentissage/ij_{{product_name}}_ui:{{app_version}}-{{env_name}}
    deploy:
      <<: *deploy-default
      resources:
        limits:
          memory: 256m
      replicas: 2
    env_file: .env_ui
    stop_grace_period: 60s
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.txt.{{product_name}}.{{env_name}}.ui
        fluentd-async: "true"

  reverse_proxy_documentation:
    <<: *default
    deploy:
      <<: *deploy-default
    image: nginx:alpine
    volumes:
      - ./documentation:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    expose:
      - "80"
    ports:
      - "8080:80"

