services:
  app:
    image: pilotage_app
    container_name: pilotage_app
    restart: "always"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ENV=recette
        - NEXT_PUBLIC_BASE_URL=https://{{ dns_name }}
        - NEXT_PUBLIC_SERVER_URL=https://{{ dns_name }}/api
        - NEXT_PUBLIC_APP_CONTAINER_URL=http://app:5000/api
        - NEXT_PUBLIC_CRISP_TOKEN={{ vault[env_type].NEXT_PUBLIC_CRISP_TOKEN }}
        - NEXT_PUBLIC_SENTRY_DSN={{ vault[env_type].SENTRY_DSN }}
        - NEXT_PUBLIC_SENTRY_AUTH_TOKEN={{ vault[env_type].SENTRY_AUTH_TOKEN }}
        - NEXT_PUBLIC_SENTRY_RELEASE={{ host_name }}_{{ git_revision }}
        - PILOTAGE_GIT_REVISION={{ git_revision }}
    depends_on:
      - postgres
    networks:
      - pilotage_network
    environment:
      - PSQL_URI={{ vault[env_type].PSQL_URI }}
      - ENV=recette
      - LOG_LEVEL=info
      - LOG_DESTINATIONS=stdout,mongodb,slack
      - PUBLIC_URL=https://{{ dns_name }}
      - HOST={{ host_name }}
      - SLACK_WEBHOOK_URL={{ vault[env_type].SLACK_WEBHOOK_URL }}
      - SLACK_TOKEN={{ vault[env_type].SLACK_TOKEN }}
      - SLACK_SIGNING_SECRET={{ vault[env_type].SLACK_SIGNING_SECRET }}
      - SLACK_CHANEL={{ vault[env_type].SLACK_CHANEL }}
      - API_KEY={{ vault[env_type].API_KEY }}
      - AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].AUTH_PASSWORD_HASH_ROUNDS }}
      - INSERJEUNES_USERNAME={{ vault[env_type].INSERJEUNES_USERNAME }}
      - INSERJEUNES_PASSWORD={{ vault[env_type].INSERJEUNES_PASSWORD }}
      - AUTH_JWT_SECRET={{ vault[env_type].AUTH_JWT_SECRET }}
      - ACTIVATION_JWT_SECRET={{ vault[env_type].ACTIVATION_JWT_SECRET }}
      - RESET_PASSWORD_JWT_SECRET={{ vault[env_type].RESET_PASSWORD_JWT_SECRET }}
      - EMAIL_FROM={{ vault[env_type].EMAIL_FROM }}
      - EMAIL={{ vault[env_type].EMAIL }}
      - SMTP_HOST={{ vault[env_type].SMTP_HOST }}
      - SMTP_PORT={{ vault[env_type].SMTP_PORT }}
      - SMTP_SECURE={{ vault[env_type].SMTP_SECURE }}
      - SMTP_AUTH_USER={{ vault[env_type].SMTP_AUTH_USER }}
      - SMTP_AUTH_PASS={{ vault[env_type].SMTP_AUTH_PASS }}
      - DNE_CODE_VERIFIER_JWT_SECRET={{ vault[env_type].DNE_CODE_VERIFIER_JWT_SECRET }}
      - DNE_CLIENT_ID={{ vault[env_type].DNE_CLIENT_ID }}
      - DNE_CLIENT_SECRET={{ vault[env_type].DNE_CLIENT_SECRET }}
      - DNE_REDIRECT_URI=https://{{ dns_name }}/api/dne_connect
      - S3_REGION={{ vault[env_type].S3_REGION }}
      - S3_BUCKET={{ vault[env_type].S3_BUCKET }}
      - S3_ENDPOINT={{ vault[env_type].S3_ENDPOINT }}
      - S3_ACCESS_KEY={{ vault[env_type].S3_ACCESS_KEY }}
      - S3_SECRET_KEY={{ vault[env_type].S3_SECRET_KEY }}
      - NOTION_TOKEN={{ vault[env_type].NOTION_TOKEN }}
      - NOTION_DB_CHANGELOG_ID={{ vault[env_type].NOTION_DB_CHANGELOG_ID }}
      - NOTION_DB_GLOSSAIRE_ID={{ vault[env_type].NOTION_DB_GLOSSAIRE_ID }}
      - NOTION_DB_EDITO_ID={{ vault[env_type].NOTION_DB_EDITO_ID }}
      - NEXT_PUBLIC_FEATURE_ETABLISSEMENT_V2=true
      - SENTRY_AUTH_TOKEN={{ vault[env_type].SENTRY_AUTH_TOKEN }}
      - SENTRY_DSN={{ vault[env_type].SENTRY_DSN }}
      - METABASE_AUTH_TOKEN={{ vault[env_type].METABASE_AUTH_TOKEN }}
      - FRANCE_TRAVAIL_CLIENT={{ vault[env_type].FRANCE_TRAVAIL_CLIENT }}
      - FRANCE_TRAVAIL_SECRET={{ vault[env_type].FRANCE_TRAVAIL_SECRET }}

  postgres:
    image: postgres:15.5
    container_name: pilotage_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - pilotage_network
    environment:
      - POSTGRES_PASSWORD={{ vault[env_type].POSTGRES_PASSWORD }}
    volumes:
      - /opt/pilotage/data/postgres/db:/var/lib/postgresql/data:z

  reverse_proxy:
    depends_on:
      - smtp

  smtp:
    image: axllent/mailpit:v1.5.5
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
      rollback_config:
        parallelism: 0
    networks:
      - pilotage_network
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - /opt/pilotage/data/mailpit:/data:z
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - MP_WEBROOT=smtp

  metabase:
    environment:
      - MB_SITE_URL=https://orion-recette.inserjeunes.beta.gouv.fr/metabase
      - DEF=ok
