version: "2.4"
services:
  server:
    environment:
      - PILOTAGE_POSTGRES_URI={{ vault[env_type].PILOTAGE_POSTGRES_URI }}
      - PILOTAGE_ENV=recette
      - PILOTAGE_LOG_LEVEL=info
      - PILOTAGE_LOG_DESTINATIONS=stdout,mongodb
      - PILOTAGE_PUBLIC_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
      - PILOTAGE_SLACK_WEBHOOK_URL={{ vault[env_type].PILOTAGE_SLACK_WEBHOOK_URL }}
      - PILOTAGE_API_KEY={{ vault[env_type].PILOTAGE_API_KEY }}
      - PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS }}
      - PILOTAGE_AUTH_USER_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_USER_JWT_SECRET }}
      - PILOTAGE_AUTH_PDS_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_PDS_JWT_SECRET }}
      - PILOTAGE_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_ACTIVATION_JWT_SECRET }}
      - PILOTAGE_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_JWT_SECRET }}
      - PILOTAGE_OVH_STORAGE_URI={{ vault[env_type].PILOTAGE_OVH_STORAGE_URI }}
      - PILOTAGE_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].PILOTAGE_OVH_STORAGE_ENCRYPTION_KEY }}
      - PILOTAGE_API_ENTREPRISE_KEY={{ vault[env_type].PILOTAGE_API_ENTREPRISE_KEY }}
      - PILOTAGE_CLAMAV_URI=clamav:3310
      - PILOTAGE_IS_OFFLINE=false
      - PILOTAGE_INSERJEUNES_USERNAME={{ vault[env_type].PILOTAGE_INSERJEUNES_USERNAME }}
      - PILOTAGE_INSERJEUNES_PASSWORD={{ vault[env_type].PILOTAGE_INSERJEUNES_PASSWORD }}

  ui:
    build:
      args:
        - NEXT_PUBLIC_ENV=recette
        - NEXT_PUBLIC_BASE_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_BASE_HOST=contrat-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_SECRET_KEY={{ vault[env_type].NEXT_PUBLIC_METABASE_SECRET_KEY }}
        - NEXT_PUBLIC_SERVER_URL=https://orion-recette.inserjeunes.beta.gouv.fr/api

  postgres:
    environment:
      - POSTGRES_PASSWORD={{ vault[env_type].PILOTAGE_POSTGRES_PASSWORD }}

  metabase:
    environment:
      - MB_SITE_URL: https://pilotage-recette.trajectoirespro.beta.gouv.fr/metabase
