version: "2.4"
services:
  server:
    environment:
      - PILOTAGE_ENV=recette
      - PILOTAGE_LOG_LEVEL=info
      - PILOTAGE_LOG_DESTINATIONS=stdout,mongodb
      - PILOTAGE_PUBLIC_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
      - PILOTAGE_MONGODB_URI={{ vault[env_type].PILOTAGE_MONGODB_URI }}
      - PILOTAGE_SLACK_WEBHOOK_URL={{ vault[env_type].PILOTAGE_SLACK_WEBHOOK_URL }}
      - PILOTAGE_API_KEY={{ vault[env_type].PILOTAGE_API_KEY }}
      - PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS }}
      - PILOTAGE_AUTH_USER_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_USER_JWT_SECRET }}
      - PILOTAGE_AUTH_PDS_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_PDS_JWT_SECRET }}
      - PILOTAGE_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_ACTIVATION_JWT_SECRET }}
      - PILOTAGE_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_JWT_SECRET }}
      - PILOTAGE_SMTP_HOST={{ vault[env_type].PILOTAGE_SMTP_HOST }}
      - PILOTAGE_SMTP_PORT={{ vault[env_type].PILOTAGE_SMTP_PORT }}
      - PILOTAGE_OVH_STORAGE_URI={{ vault[env_type].PILOTAGE_OVH_STORAGE_URI }}
      - PILOTAGE_OVH_STORAGE_ENCRYPTION_KEY={{ vault[env_type].PILOTAGE_OVH_STORAGE_ENCRYPTION_KEY }}
      - PILOTAGE_API_ENTREPRISE_KEY={{ vault[env_type].PILOTAGE_API_ENTREPRISE_KEY }}
      - PILOTAGE_CLAMAV_URI=clamav:3310
      - PILOTAGE_IS_OFFLINE=false
    depends_on:
      - smtp

  ui:
    build:
      args:
        - NEXT_PUBLIC_ENV=recette
        - NEXT_PUBLIC_BASE_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_BASE_HOST=contrat-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_URL=https://pilotage-recette.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_SECRET_KEY={{ vault[env_type].NEXT_PUBLIC_METABASE_SECRET_KEY }}

  metabase:
    environment:
      MB_SITE_URL: https://pilotage-recette.trajectoirespro.beta.gouv.fr/metabase

  smtp:
    image: mailhog/mailhog
    container_name: pilotage_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - pilotage_network
    environment:
      - MH_UI_WEB_PATH=smtp
      - MH_STORAGE=mongodb
      - MH_MONGO_URI=mongodb:27017
