version: "2.4"
services:
  app:
    image: pilotage_app
    container_name: pilotage_app
    restart: "always"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ENV=recette
        - NEXT_PUBLIC_BASE_URL=https://pilotage.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_BASE_HOST=contrat.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_URL=https://pilotage.trajectoirespro.beta.gouv.fr
        - NEXT_PUBLIC_METABASE_SECRET_KEY={{ vault[env_type].NEXT_PUBLIC_METABASE_SECRET_KEY }}
        - NEXT_PUBLIC_SERVER_URL=https://orion-recette.inserjeunes.beta.gouv.fr/api
        - NEXT_PUBLIC_APP_CONTAINER_URL=http://app:5000/api
    depends_on:
      - postgres
    networks:
      - pilotage_network
    environment:
      - PILOTAGE_POSTGRES_URI={{ vault[env_type].PILOTAGE_POSTGRES_URI }}
      - PILOTAGE_ENV=recette
      - PILOTAGE_LOG_LEVEL=info
      - PILOTAGE_LOG_DESTINATIONS=stdout,mongodb,slack
      - PILOTAGE_PUBLIC_URL=https://pilotage.trajectoirespro.beta.gouv.fr
      - PILOTAGE_SLACK_WEBHOOK_URL={{ vault[env_type].PILOTAGE_SLACK_WEBHOOK_URL }}
      - PILOTAGE_API_KEY={{ vault[env_type].PILOTAGE_API_KEY }}
      - PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_HASH_ROUNDS }}
      - PILOTAGE_AUTH_USER_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_USER_JWT_SECRET }}
      - PILOTAGE_AUTH_ACTIVATION_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_ACTIVATION_JWT_SECRET }}
      - PILOTAGE_AUTH_PASSWORD_JWT_SECRET={{ vault[env_type].PILOTAGE_AUTH_PASSWORD_JWT_SECRET }}
      - PILOTAGE_INSERJEUNES_USERNAME={{ vault[env_type].PILOTAGE_INSERJEUNES_USERNAME }}
      - PILOTAGE_INSERJEUNES_PASSWORD={{ vault[env_type].PILOTAGE_INSERJEUNES_PASSWORD }}

  postgres:
    image: postgres:14.2
    container_name: pilotage_postgres
    restart: unless-stopped
    networks:
      - pilotage_network
    environment:
      - POSTGRES_PASSWORD={{ vault[env_type].PILOTAGE_POSTGRES_PASSWORD }}
    volumes:
      - /opt/pilotage/data/postgres/db:/var/lib/postgresql/data:z

  smtp:
    image: axllent/mailpit:v1.5.5
    deploy:
      resources:
        limits:
          memory: 128m
      update_config:
        failure_action: rollback
      rollback_config:
        parallelism: 0
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - /opt/pilotage/data/mailpit:/data:z
    environment:
      - MP_DATA_FILE=/data/mailpit.db

  metabase:
    environment:
      - MB_SITE_URL=https://orion-recette.inserjeunes.beta.gouv.fr/metabase
      - DEF=ok
