export const DEMANDES_COLUMNS = {
  id: "id",
  cfd: "CFD",
  libelleDiplome: "Diplôme",
  dispositifId: "DispositifId",
  libelleDispositif: "Dispositif",
  uai: "UAI",
  libelleEtablissement: "Établissement",
  rentreeScolaire: "RS",
  typeDemande: "Type de demande",
  motif: "Motif",
  autreMotif: "Autre motif",
  coloration: "Coloration",
  libelleColoration: "Libelle coloration",
  amiCma: "AMI/CMA ?",
  poursuitePedagogique: "Poursuite pédagogique ?",
  commentaire: "Commentaire",
  status: "Status",
  codeRegion: "CodeRegion",
  codeAcademie: "CodeAcadémie",
  createdAt: "Date de création",
  compensationCfd: "CFD compensé",
  compensationUai: "UAI compensé",
  compensationDispositifId: "Dispositif compensé",
} as const;
