export const ETABLISSEMENTS_COLUMNS = {
  libelleEtablissement: "Nom d'établissement",
  commune: "Commune",
  departement: "Département",
  libelleNiveauDiplome: "Diplome",
  libelleDiplome: "Formation",
  effectif1: "Effectif 1",
  effectif2: "Effectif 2",
  effectif3: "Effectif 3",
  capacite: "Capacité",
  tauxPression: "Tx de pression",
  tauxRemplissage: "Tx de remplissage",
  premiersVoeux: "Nb premiers voeux",
  tauxPoursuiteEtudes: "Tx de poursuite d'études",
  valeurAjoutee: "Valeur ajoutée",
  decrochage: "Décrochage",
  secteur: "Secteur",
  UAI: "UAI",
  libelleDispositif: "Dispositif",
  libelleOfficielFamille: "Famille de métiers",
} as const;
