export const FORMATIONS_COLUMNS = {
  rentreeScolaire: "RS",
  libelleNiveauDiplome: "Diplome",
  libelleDiplome: "Formation",
  nbEtablissement: "Nb Etab",
  effectif1: "Année 1",
  effectif2: "Année 2",
  effectif3: "Année 3",
  tauxPression: "Tx de pression",
  tauxRemplissage: "Tx de remplissage",
  tauxInsertion6mois: "Tx d'emploi 6 mois régional",
  tauxPoursuiteEtudes: "Tx de poursuite d'études régional",
  libelleDispositif: "Dispositif",
  libelleOfficielFamille: "	Famille de métiers",
  codeFormationDiplome: "CodeDiplome",
  CPC: "CPC",
  CPCSecteur: "CPCSecteur",
  CPCSousSecteur: "CPCSousSecteur",
  libelleFiliere: "Secteur d’activité",
} as const;
