export const FORMATIONS_COLUMNS = {
  libelleNiveauDiplome: "Diplome",
  libelleDiplome: "Formation",
  nbEtablissement: "Nb Etab",
  effectif1: "Effectif 1",
  effectif2: "Effectif 2",
  effectif3: "Effectif 3",
  tauxInsertion12mois: "Tx d'emploi 12 mois",
  deltaInsertion6mois: "Delta régional insertion",
  tauxPoursuiteEtudes: "Tx de poursuite d'études	",
  deltaPoursuiteEtudes: "Delta régional poursuite	",
  libelleDispositif: "Dispositif",
  libelleOfficielFamille: "	Famille de métiers",
  CodeFormationDiplome: "CodeDiplome",
  decrochage: "Décrochage",
} as const;
