export const FORMATIONS_COLUMNS = {
  rentreeScolaire: "RS",
  libelleNiveauDiplome: "Diplôme",
  libelleDiplome: "Formation",
  nbEtablissement: "Nb Etab",
  effectif1: "Année 1",
  effectif2: "Année 2",
  effectif3: "Année 3",
  tauxPression: "Tx de pression",
  tauxRemplissage: "Tx de remplissage",
  tauxInsertion6mois: "Tx d'emploi 6 mois régional",
  tauxPoursuiteEtudes: "Tx de poursuite d'études régional",
  libelleDispositif: "Dispositif",
  libelleOfficielFamille: "	Famille de métiers",
  codeFormationDiplome: "Code diplôme",
  CPC: "CPC",
  CPCSecteur: "CPCSecteur",
  CPCSousSecteur: "CPCSousSecteur",
  libelleFiliere: "Secteur d’activité",
  "continuum.libelle": "Diplôme historique",
  "continuum.cfd": "Code diplôme historique",
} as const;
