export const STATS_DEMANDES_COLUMNS = {
  id: "N° demande",
  cfd: "CFD",
  libelleDiplome: "Formation",
  dispositifId: "DispositifId",
  niveauDiplome: "Diplôme",
  libelleDispositif: "Dispositif",
  uai: "UAI",
  libelleEtablissement: "Établissement",
  rentreeScolaire: "RS",
  typeDemande: "Type de demande",
  motifs: "Motif(s) de la demande",
  autreMotif: "Autre motif",
  coloration: "Coloration",
  libelleColoration: "Libellé coloration",
  libelleFCIL: "Libellé FCIL",
  amiCma: "AMI/CMA ?",
  poursuitePedagogique: "Poursuite pédagogique ?",
  commentaire: "Commentaire",
  libelleFiliere: "Filière",
  status: "Status",
  codeRegion: "CodeRegion",
  libelleRegion: "Région",
  codeDepartement: "CodeDepartement",
  libelleDepartement: "Département",
  codeAcademie: "CodeAcadémie",
  createdAt: "Date de création",
  compensationCfd: "CFD compensé",
  compensationUai: "UAI compensé",
  compensationDispositifId: "Dispositif compensé",
  differenceCapaciteScolaire: "Nombre de places en voie scolaire",
  capaciteScolaireActuelle: "Capacité scolaire actuelle",
  capaciteScolaire: "Capacité scolaire",
  capaciteScolaireColoree: "Capacité scolaire coloree",
  differenceCapaciteApprentissage: "Nombre de places en apprentissage",
  capaciteApprentissageActuelle: "Capacité apprentissage actuelle",
  capaciteApprentissage: "Capacité apprentissage",
  capaciteApprentissageColoree: "Capacité apprentissage coloree",
  insertion: "Tx d'emploi à 6 mois régional",
  poursuite: "Tx de poursuite d'études régional",
  devenirFavorable: "Tx de devenir favorable régional",
  pression: "Tx de pression régional",
  nbEtablissement: "Nb établissement",
} as const;
