export const STATS_DEMANDES_COLUMNS = {
  id: "id",
  cfd: "CFD",
  libelleDiplome: "Formation",
  dispositifId: "DispositifId",
  niveauDiplome: "Diplôme",
  libelleDispositif: "Dispositif",
  uai: "UAI",
  libelleEtablissement: "Établissement",
  rentreeScolaire: "RS",
  typeDemande: "Type de demande",
  motifs: "Motif(s) de la demande",
  autreMotif: "Autre motif",
  coloration: "Coloration",
  libelleColoration: "Libellé coloration",
  libelleFCIL: "Libellé FCIL",
  amiCma: "AMI/CMA ?",
  poursuitePedagogique: "Poursuite pédagogique ?",
  commentaire: "Commentaire",
  libelleFiliere: "Filière",
  status: "Status",
  codeRegion: "CodeRegion",
  libelleRegion: "Région",
  codeDepartement: "CodeDepartement",
  libelleDepartement: "Département",
  codeAcademie: "CodeAcadémie",
  createdAt: "Date de création",
  compensationCfd: "CFD compensé",
  compensationUai: "UAI compensé",
  compensationDispositifId: "Dispositif compensé",
  differenceCapaciteScolaire: "Différence de capacité scolaire",
  capaciteScolaireActuelle: "Capacité scolaire actuelle",
  capaciteScolaire: "Capacité scolaire",
  capaciteScolaireColoree: "Capacité scolaire coloree",
  differenceCapaciteApprentissage: "Différence de capacité en apprentissage",
  capaciteApprentissageActuelle: "Capacité apprentissage actuelle",
  capaciteApprentissage: "Capacité apprentissage",
  capaciteApprentissageColoree: "Capacité apprentissage coloree",
  insertion: "Taux d'insertion régional",
  poursuite: "Taux de poursuite d'études régional",
  devenirFavorable: "Taux de devenir favorable régional",
  pression: "Taux de pression de la formation au niveau régional",
  nbEtablissement:
    "Nb établissements dispensant la formation dans la région en 2022",
} as const;
