import { z } from "zod";

export const ChangelogTypeZodType = z.enum(["BANDEAU", "Fonctionnalité", "Données", "Bug"]);

export const ChangelogTypeEnum = ChangelogTypeZodType.Enum;

export type ChangelogTypeType = z.infer<typeof ChangelogTypeZodType>;

export interface IChangelog {
    id: string,
    title: string,
    deployed: boolean,
    types: ChangelogTypeType[],
    date: Date,
    description: string,
    document?: string,
    show: boolean,
}

export const CHANGELOG: IChangelog[] = [
  {
    "id": "18cd0d8ec0158002aa65e8acae3243f1",
    "deployed": true,
    "show": false,
    "title": "Constat de rentrée 2024 et Taux IJ 2022-2023",
    "types": [ChangelogTypeEnum.BANDEAU],
    "date": new Date("2025-01-31"),
    "description": "Le constat de rentrée 2024 est chargé ainsi que le dernier millésime InserJeunes. Ces données modifient la position des formations dans les quadrants et ont un impact sur le calcul du taux de transformation.",
    "document": "",
  },
  {
    "id": "18fd0d8ec015800da79de853d1811d9b",
    "deployed": true,
    "show": true,
    "title": "Constat de rentrée 2024 et taux IJ 2022-2023",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2025-02-03"),
    "description": "Accédez aux effectifs 2024 dans les consoles Formations et Etablissements ainsi que dans les panorama. Le constat de rentrée 2024 fait également évoluer le Taux de transformation car les effectifs sont pris en compte dans le dénominateur.\nLe millésime 2022-2023 des taux InserJeunes est en ligne, les positions des formations dans les différents quadrants sont donc impactées, ce nouveau millésime est également celui qui est affiché dans les consoles.",
    "document": "",
  },
  {
    "id": "18cd0d8ec01580a286e8e9e722a0439c",
    "deployed": true,
    "show": false,
    "title": "Panorama Domaine de formation",
    "types": [ChangelogTypeEnum.BANDEAU],
    "date": new Date("2025-01-09"),
    "description": "Découvrez le Panorama Domaine de Formation, qui vous permet de visualiser quelles sont les formations dispensées ou absentes sur votre territoire.",
    "document": "",
  },
  {
    "id": "18fd0d8ec01580cbb706e4f61fa95497",
    "deployed": true,
    "show": true,
    "title": "Nouveau Panorama Domaine de formation",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2025-01-09"),
    "description": "Observez l’évolution des taux d’emploi et de poursuite d’’études, visualisez l’offre de formations sur une carte, identifiez les formations qui sont dispensées ou non sur le territoire observé.",
    "document": "",
  },
  {
    "id": "176d0d8ec01580d4b9aefab78f319cd1",
    "deployed": true,
    "show": false,
    "title": "Mise à jour technique",
    "types": [ChangelogTypeEnum.BANDEAU],
    "date": new Date("2024-12-10"),
    "description": "Certains utilisateurs rencontrent des problèmes pour afficher la cartographie de la page établissement. Si c’est votre cas, veuillez rafraichir Orion en vidant votre cache.",
    "document": "",
  },
  {
    "id": "158d0d8ec015802db8f4d44911441648",
    "deployed": true,
    "show": false,
    "title": "Accès",
    "types": [ChangelogTypeEnum.BANDEAU],
    "date": new Date("2025-06-04"),
    "description": "Attention : sur les panoramas régional et départemental, les chiffres sont désormais affichés par niveau de diplôme (Bac Pro par défaut). Vous pouvez choisir le diplôme que vous souhaitez.",
    "document": "https://aide.orion.inserjeunes.beta.gouv.fr/fr/article/experimentation-occitanie-auvergne-rhone-alpes-visio-chefs-detablissement-1apg5m6/",
  },
  {
    "id": "b34ab1a26e394c46b893e973e60ff68f",
    "deployed": true,
    "show": true,
    "title": "Accès",
    "types": [ChangelogTypeEnum["Fonctionnalité"]],
    "date": new Date("2024-05-14"),
    "description": "L'accès en mode public permet de découvrir les données sur la formation professionnelle selon les régions, départements, établissements. Un accès en mode connecté est réservé aux Recteur et DRAFPIC (d'autres accès seront fournis directement par les RA dans quelques semaines). L'accès pour les chefs d'établissement se fait par le portail Arena. Ils peuvent donner délégation à d’autres personnels (adjoint, DDFTP…). N'hésitez pas à nous contacter si vous avez besoin de renseignements.",
    "document": "https://aide.orion.inserjeunes.beta.gouv.fr/fr/article/acceder-a-orion-rmfohn/",
  },
  {
    "id": "176d0d8ec01580a0bbd7db7856c53f56",
    "deployed": true,
    "show": true,
    "title": "Nouveau Panorama Etablissement",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-04-04"),
    "description": "Découvrez la cartographie de toute l’offre de formation, y compris en apprentissage.",
    "document": "",
  },
  {
    "id": "b04441c1b6d3422c8ee6c1a72d116016",
    "deployed": true,
    "show": true,
    "title": "Effectifs 2023",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-02-13"),
    "description": "Les effectifs sont mis à jour dans toutes les pages, sur la base du Constat de rentrée 2023. \nAttention, cette mise à jour a un impact sur le calcul du taux de transformation.",
    "document": "",
  },
  {
    "id": "ae36f693dad14a4794032d5072955fd6",
    "deployed": true,
    "show": true,
    "title": "Taux emploi et poursuite d’études 2022 (taux InserJeunes)",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-01-21"),
    "description": "Orion intègre désormais les données sur les sortants 2022. Le taux d’emploi 2022 inclut les embauches dans le secteur public ce qui modifie sensiblement le taux de certaines formations, dans le secteur santé-social notamment.\nLe taux de poursuite d’études a également été mis à jour.\nPour rappel le taux d’emploi porte sur le cumul de deux cohortes, soit les sortants 2021_2022.",
    "document": "",
  },
  {
    "id": "771fd101b14140299075f8759600a594",
    "deployed": true,
    "show": true,
    "title": "Affichage des 2ndes communes",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-01-21"),
    "description": "Orion affiche désormais les 2ndes communes pour les Bacs Pro en Famille de métiers. Vous pouvez ainsi visualiser l’effectif en entrée et la répartition par spécialité par établissement.",
    "document": "",
  },
  {
    "id": "3005769537f24da1aa644d4d0bdb3ab5",
    "deployed": true,
    "show": true,
    "title": "Affichage des formations “historiques”",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-01-21"),
    "description": "Les formations pré-existantes aux formations  rénovées et qui sont toujours proposées (fin de cohorte) sont visibles dans les consoles Formations et Etablissement. Vous pouvez ainsi visualiser l’exhaustivité des formations proposées et des effectifs. Cela vous permet également d’accéder aux taux d’emploi et de poursuite d’études lorsque ces taux ne sont disponibles sur la nouvelle formation (= formation rénovée).",
    "document": "",
  },
  {
    "id": "c6bc6bd1b5fc4b449253be9f89f03870",
    "deployed": true,
    "show": true,
    "title": "Panorama Etablissement",
    "types": [ChangelogTypeEnum["Fonctionnalité"]],
    "date": new Date("2024-04-04"),
    "description": "Rendez-vous dans l’onglet Etablissement du panorama pour accéder à des data-visualisations détaillées des formations d’un établissement ainsi qu’une cartographie de toutes les formations en voie professionnelle initiale et en apprentissage.",
    "document": "",
  },
  {
    "id": "2217ee9a9fbb4965b74cbfc610bf89e4",
    "deployed": true,
    "show": true,
    "title": "Domaine de formation (NSF)",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-03-05"),
    "description": "Nous avons remplacé la donnée “Secteur d’activité” par la Nomenclature des Spécialités de Formation (NSF), que vous retrouverez sous le terme “Domaine de formation (NSF)”. Cela permet de regrouper les formations d’un même domaine de manière plus exhaustive. Cela permettra également de regrouper les formations en apprentissage et les formations en voie scolaire d’un même domaine (à venir début avril).",
    "document": "",
  },
  {
    "id": "d389ff6eac4845bf91d1827e54c84a32",
    "deployed": true,
    "show": true,
    "title": "Apprentissage",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-04-03"),
    "description": "L’offre de formation en apprentissage est intégrée à Orion, à partir du catalogue du Réseau des Carif Oref, complétée par les taux InserJeunes. Elle est consultable uniquement via la cartographie du Panorama Etablissement, pour le moment.",
    "document": "",
  },
  {
    "id": "1a7242e2b1134cd4814f82c8a92512d4",
    "deployed": true,
    "show": true,
    "title": "Ouverture de la campagne 2024",
    "types": [ChangelogTypeEnum["Fonctionnalité"]],
    "date": new Date("2024-06-04"),
    "description": "Le formulaire qui permet la saisie  des demandes d’ouverture et fermeture pour la rentrée 2025 est ouvert pour toutes les régions sauf Occitanie et AURA pour lesquelles le formulaire sera livré le 5 juin après-midi.",
    "document": "",
  },
  {
    "id": "90eebf4ab4a943fdb32b11ee628bc75f",
    "deployed": true,
    "show": true,
    "title": "Panorama et console : position dans le quadrant",
    "types": [
      ChangelogTypeEnum["Données"],
      ChangelogTypeEnum["Fonctionnalité"]
    ],
    "date": new Date("2024-04-06"),
    "description": "Le quadrant affiche les formations pour lesquelles les taux d’emplois et de poursuite d’étude sont disponibles. Le panorama (régional et départemental) sont ainsi préfiltrés sur le niveau Bac pro, vous pouvez modifier en haut de page. Pour la console, la position du quadrant s’affiche si une région est sélectionnée.",
    "document": "",
  },
  {
    "id": "12fd0d8ec01580208c20d730e619479d",
    "deployed": true,
    "show": true,
    "title": "Transformation : la position dans le quadrant est liée à la campagne",
    "types": [ChangelogTypeEnum["Données"]],
    "date": new Date("2024-10-30"),
    "description": "Afin de pouvoir évaluer l’impact de la transformation, la position dans le quadrant est liée à la campagne dans les pages de l’onglet Transformation. Pour illustrer, si vous saisissez une ouverture sur une formation en Q3 au moment de la saisie, cette donnée n’évoluera pas lorsque vous reviendrez sur la fiche synthèse de cette demande à postériori.",
    "document": "",
  },
  {
    "id": "158d0d8ec015805aafa3d421c1ee2b03",
    "deployed": true,
    "show": true,
    "title": "Mise à jour technique de l’outil de visualisation des cartes dans Orion",
    "types": [ChangelogTypeEnum["Bug"]],
    "date": new Date("2024-10-30"),
    "description": "Suite à une mise à jour technique, certains utilisateurs ne voient plus la carte dans la page établissement. Si c’est votre cas, un simple rafraichissement de la page en vidant le cache permet de corriger le problème. Si vous êtes sur Windows, vous pouvez effectuer Ctrl + F5. Si vous êtes sur MacOS vous pouvez effectuer Command + Maj + R.",
    "document": "",
  },
  {
    "id": "133d1a0c-4cf6-44ad-b775-5a09683aa242",
    "deployed": true,
    "show": true,
    "title": "Ajout du taux de transformation cumulé",
    "types": [ChangelogTypeEnum["Fonctionnalité"]],
    "date": new Date("2025-03-10"),
    "description": "Le taux de transformation cumulé depuis 2023 est affiché dans la page suivi de l’impact.",
    "document": "",
  },
  {
    "id": "d825aa75-94d9-48d8-b777-49cd5f67909f",
    "deployed": true,
    "show": true,
    "title": "Introduction des campagnes régionales",
    "types": [ChangelogTypeEnum["Fonctionnalité"]],
    "date": new Date("2025-03-03"),
    "description": "Les campagnes sont désormais gérées au niveau régional. C’est l’admin Orion en R.A. qui ouvre et ferme les campagnes en précisant si les chefs d’établissement saisissent les propositions ou non.",
    "document": "",
  },
  {
    "id": "ad424ff3-be91-44f7-910f-864f36c6c8a6",
    "deployed": true,
    "show": true,
    "title": "Erreur dans les données d’apprentissage",
    "types": [ChangelogTypeEnum["BANDEAU"]],
    "date": new Date("2025-04-23"),
    "description": "Erreurs sur la page Domaine de Formation : suite à une mise à jour des données “apprentissage”, la page Domaine de formation affiche des données erronées : nombre d’établissements et nombre d’élèves en entrée. Les taux InserJeunes sont exacts. Le problème est en cours de résolution.",
    "document": "",
  },
  {
    "id": "84981ee7-5930-4cb2-8a8e-026892c67a79",
    "deployed": true,
    "show": true,
    "title": "Erreur données apprentissage (Domaine de formation)",
    "types": [ChangelogTypeEnum["Bug"]],
    "date": new Date("2025-04-23"),
    "description": "Erreurs sur la page Domaine de Formation : suite à une mise à jour des données “apprentissage”, la page Domaine de formation affiche des données erronées : nombre d’établissements et nombre d’élèves en entrée. Les taux InserJeunes sont exacts. Le problème est en cours de résolution.",
    "document": "",
  },
];
