export const GLOSSAIRE_ENTRIES_KEYS = {
  ["action-prioritaire"]: "action-prioritaire",
  ["ami-cma"]: "ami-cma",
  ["apprentissage"]: "apprentissage",
  ["capacite"]: "capacite",
  ["cmq"]: "cmq",
  ["DEPP"]: "depp",
  ["domaine-de-formation-nsf"]: "domaine-de-formation-nsf",
  ["domaine-professionnel-emploi"]: "domaine-professionnel-rome",
  ["effectif-en-entree"]: "effectif-en-entree",
  ["fcil"]: "fcil",
  ["formation-historique-renovee"] : 'formation-historique-renovee',
  ["formation-mixte"] : 'formation-mixte',
  ["formation-specifique"]: "formation-specifique",
  ["inserjeunes"]: "inserjeunes",
  ["millesime"]: "millesime",
  ["nombre-deleves"]: "nombre-deleves",
  ["professeur-associe"]: "professeur-associe",
  ["quadrant"]: "quadrant-q1-a-q4",
  ["taux-de-demande"]: "taux-de-demande",
  ["taux-de-devenir-favorable"]: "taux-de-devenir-favorable",
  ["taux-de-pression"]: "taux-de-pression",
  ["taux-de-remplissage"]: "taux-de-remplissage",
  ["taux-emploi-6-mois"]: "taux-emploi-6-mois",
  ["taux-poursuite-etudes"]: "taux-poursuite-d-etudes",
  ["tension-difficulte-de-recrutement"]: "tension-difficulte-de-recrutement",
  ["valeur-ajoutee"]: "valeur-ajoutee",
  ["voeux"]: "voeux",
  ["metier-en-tension"]: "metier-en-tension",
  ["metier-rome"]: "metier-rome",
  ["coloration"]: "coloration",
  ["transition-demographique"]: "transition-demographique",
  ["transition-ecologique"]: "transition-ecologique",
  ["transition-numerique"]: "transition-numerique",
};

export type GlossaireEntryKey = keyof typeof GLOSSAIRE_ENTRIES_KEYS;
