name: Deployment
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Le type de Release Candidate à générer
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
  workflow_call:
    inputs:
      release_type:
        description: Le type de Release Candidate à générer
        type: string
        required: false

jobs:
  deploy:
    name: Generate ${{ inputs.release_type }} RC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Run playbook
        run: .bin/product release:generate:rc-label ${{ inputs.release_type }} >> $GITHUB_OUTPUT
