name: Server uptime
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Get server Uptime
        type: choice
        required: true
        options:
          - production
          - recette1
          - recette2
  workflow_call:
    inputs:
      environment:
        description: The environment to check on
        type: string
        default: latest
        required: false
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      DEPLOY_PASS:
        description: SSH PWD TO DEPLOY
        required: true

jobs:
  deploy:
    name: Uptim on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github_actions
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          config: |
            Host *
              IdentityFile ~/.ssh/github_actions
          if_key_exists: replace

      - name: Get env ip
        run: echo "IP_ADDRESS=$(awk '/^\[${{ inputs.environment }}\]/{getline; print}' .infra/env.ini" >> $GITHUB_ENV
      
      - name: uptime over SSH
        run: ssh deploy@$IP_ADDRESS "uptime"

