name: Release version develop
on:
  push:
    branches: [develop_leg]

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'chore(release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 16.6.0
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Run yarn Install
        run: yarn install

      - name: bump
        run: yarn npm:release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  # deploy:
  #   needs: release
  #   if: "!startsWith(github.event.head_commit.message, 'chore(release')"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v2

  #     - shell: bash
  #       run: echo 'PILOTAGE_HEAD_REF=${{ github.head_ref }}' >> $GITHUB_ENV

  #     - shell: bash
  #       run: echo 'PILOTAGE_REF=${{ github.ref }}' >> $GITHUB_ENV

  #     - name: Check output
  #       run: echo ${PILOTAGE_REF:-${PILOTAGE_REF##*/}}

  #     - name: Request deployment recette
  #       uses: peter-evans/repository-dispatch@v1
  #       with:
  #         repository: mission-apprentissage/PILOTAGE-infra
  #         token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
  #         event-type: deploy
  #         client-payload: '{"envName": "recette", "branchName":"develop"}'
  #       if: github.ref == 'refs/heads/develop'
