name: Yarn CI
on: [pull_request]
jobs:
  ciserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Get branch name
        id: branch_name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME="${BRANCH_NAME//\//-}"
          BRANCH_NAME="${BRANCH_NAME// /-}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - run: make ci

      - name: Build project
        env:
          NEXT_PUBLIC_BASE_URL: ${{ vars.BASE_URL }}
          NEXT_PUBLIC_ENV: ${{ vars.ENV }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          NEXT_PUBLIC_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_SENTRY_RELEASE: ci-${{ steps.branch_name.outputs.branch }}
        run: make build
