name: Yarn CI
on: [pull_request]
jobs:
  ciserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - run: make ci
