stages:
  - ci

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: "fast"

.node_setup:
  image: node:22
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .yarn/install-state.gz
      - .yarn/cache/
    policy: pull-push
  before_script:
    - corepack enable
    - yarn install

typecheck:
  extends: .node_setup
  stage: ci
  script:
    - yarn typecheck:ci
  timeout: 10 minutes

tests:
  extends: .node_setup
  stage: ci
  services:
    - docker:dind
  before_script:
    - corepack enable
    - yarn install
    - yarn dedupe --check
  script:
    - yarn lint:ci
    - docker compose up -d --wait postgres
    - yarn test:ci
  timeout: 10 minutes
